"""empty message

Revision ID: e19f1bfc12b4
Revises: fc92c06a78ad
Create Date: 2024-08-11 19:04:29.704071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19f1bfc12b4'
down_revision = 'fc92c06a78ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('id_gender', sa.Integer(), nullable=False),
    sa.Column('id_color', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_color'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['id_gender'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('total', sa.Double(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothe_advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clothe', sa.Integer(), nullable=False),
    sa.Column('id_advertisement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_advertisement'], ['advertisements.id'], ),
    sa.ForeignKeyConstraint(['id_clothe'], ['clothes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothe_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clothe', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clothe'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_clothe', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_clothe'], ['clothes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('clothe_orders')
    op.drop_table('clothe_advertisements')
    op.drop_table('orders')
    op.drop_table('clothes')
    op.drop_table('users')
    # ### end Alembic commands ###
